name: mlopspython_ci

dependencies:

- r
- r-essentials
- numpy
- pandas
- scikit-learn

- pip
- pip:

  # dependencies shared with diabetes_regression/scoring/scoring_dependencies.yml.
  # Versions specification must match exactly, or the docker build will fail.
  - azureml-sdk==1.0.74

  # Additional pip dependencies for the CI environment.
  - pytest>=5.3
  - requests>=2.22
  - numpy>=1.17
  - python-dotenv>=0.10.3
  - flake8>=3.7
  - flake8_formatter_junit_xml
  - azure-cli>=2.0.76
