pr: none
trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: mlopscr.azurecr.io/public/mlops/mlopspython:latest
  endpoint: acrconnection


variables:
- group: devopsforai-aml-vg


steps:
- script: |
   ls -ltr
   echo 'hi'
   flake8 --output-file=$(Build.BinariesDirectory)/flake8_amlservice_testresults.xml
   #flake8 --output-file=$(Build.BinariesDirectory)/flake8_tests_testresults.xml tests
   cat $(Build.BinariesDirectory)/flake8_amlservice_testresults.xml
   ls -ltr $(Build.BinariesDirectory)
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Run code quality tests'
  enabled: 'true'

    
- bash: |
   # Invoke the Python training pipeline
   python3 $(Build.SourcesDirectory)/aml_pipelines/model_train_pipeline.py
  failOnStderr: 'false'
  env:
    SP_APP_SECRET: '$(SP_APP_SECRET)'
  displayName: 'Train model using AML with Remote Compute'
  enabled: 'true'