trigger: none
pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  baseName: $[coalesce(variables['baseNameOverride'],  'pythonml')]
  containerRegistry: $[coalesce(variables['acrServiceConnection'], 'acrconnection')]
  imageName: $[coalesce(variables['builderImageName'], 'mlopsbuildagent')]  


steps:
  - template: templates/docker-builder-image-template.yml
